#CI/CD
name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: 3.19.246.147
        username: ubuntu
        key: ${{ secrets.OMG_SECRET }}
        port: 22
        script: |
          cd /var/www/html/cvvlogs-backend-new
          cp /var/www/html/.env /var/www/html/cvvlogs-backend-new
          git pull origin master
          git status
          sudo chmod 777 storage/